name: updatesPersonalWebsite

on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Backwards
              run: |
                cd ../
            - name: Clone HugoGitIoPersonalServer
              uses: GuillaumeFalourd/clone-github-repo-action@v2.2
              with:
                owner: 'Xcanton'
                repository: 'HugoGitIoPersonalServer'
                access-token: ${{ secrets.PersonalWebsite  }}
            - name: Update
              run: |
                cd HugoGitIoPersonalServer
                sh codes/GitPush.sh
            - name: Delete
              run: |
                cd ../
                rm -rf ./HugoGitIoPersonalServer
